### PR TITLE
Reduce bulk and few edits

### PR DESCRIPTION
**Pull request by mblue9**

### CODE REVIEW

**Comment by mblue9** [comment]
Thanks for that filter fix! 
If you could have a quick look at this PR when you get a chance and let me know if we can merge, then we can see where we're at with this material/ how it looks/ any other changes needed.

**Review by stemangiola — COMMENTED** [review]
Is it possible to point directly to 

https://github.com/stemangiola/tidySummarizedExperiment/releases/tag/v1.2.0 
https://github.com/stemangiola/tidybulk/releases/tag/v1.4.0
https://github.com/stemangiola/tidySingleCellExperiment/releases/tag/v1.3.0

so the compilation would not fail in case of destructive updates? (I will keep destruction to the inimum)

**Comment by mblue9** [comment]
>Is it possible to point directly to

>https://github.com/stemangiola/tidySummarizedExperiment/releases/tag/v1.2.0
>https://github.com/stemangiola/tidybulk/releases/tag/v1.4.0
>https://github.com/stemangiola/tidySingleCellExperiment/releases/tag/v1.3.0

>so the compilation would not fail in case of destructive updates? (I will keep destruction to the inimum)

Ok I've specified those here.

**Comment by mblue9** [comment]
If this passes I'll merge.
One other question- should I set ISMB workshop to use these package versions too?

**Comment by stemangiola** [comment]
Amazing. Yes same ones.

**Pull request merged**
